# Form implementation generated from reading ui file 'Page_Simulator.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1362, 940)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: #2d2d2d;")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=MainWindow)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 410, 1061, 501))
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"    background-color: #1e1e1e;\n"
"    border-radius: 5px;\n"
"    border: 1px solid #555;\n"
"}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.Added_Page = QtWidgets.QFrame(parent=self.groupBox_3)
        self.Added_Page.setGeometry(QtCore.QRect(380, 80, 311, 400))
        self.Added_Page.setMinimumSize(QtCore.QSize(191, 400))
        self.Added_Page.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Added_Page.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Added_Page.setObjectName("Added_Page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Added_Page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(parent=self.Added_Page)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.New_Process = QtWidgets.QFrame(parent=self.groupBox_3)
        self.New_Process.setGeometry(QtCore.QRect(720, 80, 311, 400))
        self.New_Process.setMinimumSize(QtCore.QSize(191, 400))
        self.New_Process.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.New_Process.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.New_Process.setObjectName("New_Process")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.New_Process)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(parent=self.New_Process)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.Current_Process = QtWidgets.QFrame(parent=self.groupBox_3)
        self.Current_Process.setGeometry(QtCore.QRect(40, 80, 311, 400))
        self.Current_Process.setMinimumSize(QtCore.QSize(191, 400))
        self.Current_Process.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Current_Process.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Current_Process.setObjectName("Current_Process")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Current_Process)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=self.Current_Process)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.label_15 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(20, 10, 161, 20))
        self.label_15.setStyleSheet("color: white;\n"
"font-size: 16px;\n"
"border: 0;\n"
"background-color: #1e1e1e;\n"
"\n"
"")
        self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.label_22 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(40, 40, 311, 23))
        self.label_22.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        border: 0;\n"
"        background-color: #1e1e1e;\n"
"}")
        self.label_22.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(380, 40, 311, 23))
        self.label_23.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        border: 0;\n"
"        background-color: #1e1e1e;\n"
"}")
        self.label_23.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(720, 40, 311, 23))
        self.label_24.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        border: 0;\n"
"        background-color: #1e1e1e;\n"
"}")
        self.label_24.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.frame_5 = QtWidgets.QFrame(parent=MainWindow)
        self.frame_5.setGeometry(QtCore.QRect(30, 60, 821, 221))
        self.frame_5.setStyleSheet("background-color: #1e1e1e;\n"
"border-radius: 5px;\n"
"border: 1px solid #555;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_10 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_10.setGeometry(QtCore.QRect(20, 10, 361, 20))
        self.label_10.setStyleSheet("color: white;\n"
"font-size: 16px;\n"
"border: 0;\n"
"")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label = QtWidgets.QLabel(parent=self.frame_5)
        self.label.setGeometry(QtCore.QRect(20, 50, 71, 31))
        self.label.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        border: 0;\n"
"}")
        self.label.setObjectName("label")
        self.Length_Line_Edit = QtWidgets.QLineEdit(parent=self.frame_5)
        self.Length_Line_Edit.setGeometry(QtCore.QRect(130, 40, 271, 41))
        self.Length_Line_Edit.setAutoFillBackground(False)
        self.Length_Line_Edit.setStyleSheet("QLineEdit {\n"
"    background-color: #2d2d2d;\n"
"    color: white;\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    padding: 4px;\n"
"    font-size: 16px;\n"
"}")
        self.Length_Line_Edit.setObjectName("Length_Line_Edit")
        self.Frame_Line_Edit = QtWidgets.QLineEdit(parent=self.frame_5)
        self.Frame_Line_Edit.setGeometry(QtCore.QRect(130, 100, 271, 41))
        self.Frame_Line_Edit.setAutoFillBackground(False)
        self.Frame_Line_Edit.setStyleSheet("QLineEdit {\n"
"    background-color: #2d2d2d;\n"
"    color: white;\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    padding: 4px;\n"
"    font-size: 16px;\n"
"}")
        self.Frame_Line_Edit.setMaxLength(32773)
        self.Frame_Line_Edit.setObjectName("Frame_Line_Edit")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 71, 31))
        self.label_2.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        border: 0;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.Generate_Button = QtWidgets.QPushButton(parent=self.frame_5)
        self.Generate_Button.setGeometry(QtCore.QRect(20, 160, 381, 41))
        self.Generate_Button.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #121212;\n"
"}")
        self.Generate_Button.setObjectName("Generate_Button")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_3.setGeometry(QtCore.QRect(425, 40, 131, 41))
        self.label_3.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        border: 0;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.Reference_String_Line_Edit = QtWidgets.QLineEdit(parent=self.frame_5)
        self.Reference_String_Line_Edit.setGeometry(QtCore.QRect(420, 100, 381, 41))
        self.Reference_String_Line_Edit.setStyleSheet("QLineEdit {\n"
"    background-color: #2d2d2d;\n"
"    color: white;\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    padding: 4px;\n"
"    font-size: 16px;\n"
"}")
        self.Reference_String_Line_Edit.setObjectName("Reference_String_Line_Edit")
        self.Confirm_Button = QtWidgets.QPushButton(parent=self.frame_5)
        self.Confirm_Button.setGeometry(QtCore.QRect(690, 160, 111, 41))
        self.Confirm_Button.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #121212;\n"
"}")
        self.Confirm_Button.setObjectName("Confirm_Button")
        self.label_9 = QtWidgets.QLabel(parent=MainWindow)
        self.label_9.setGeometry(QtCore.QRect(0, 20, 1311, 20))
        self.label_9.setStyleSheet("color: white;\n"
"font-size: 20px;\n"
"")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.frame_6 = QtWidgets.QFrame(parent=MainWindow)
        self.frame_6.setGeometry(QtCore.QRect(870, 60, 221, 221))
        self.frame_6.setStyleSheet("background-color: #1e1e1e;\n"
"border-radius: 5px;\n"
"border: 1px solid #555;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_11 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_11.setGeometry(QtCore.QRect(20, 10, 161, 20))
        self.label_11.setStyleSheet("color: white;\n"
"font-size: 16px;\n"
"border: 0;\n"
"")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.LRU_Button = QtWidgets.QPushButton(parent=self.frame_6)
        self.LRU_Button.setGeometry(QtCore.QRect(20, 100, 181, 41))
        self.LRU_Button.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #121212;\n"
"}")
        self.LRU_Button.setObjectName("LRU_Button")
        self.Optimal_Button = QtWidgets.QPushButton(parent=self.frame_6)
        self.Optimal_Button.setGeometry(QtCore.QRect(20, 160, 181, 41))
        self.Optimal_Button.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #121212;\n"
"}")
        self.Optimal_Button.setObjectName("Optimal_Button")
        self.FIFO_Button = QtWidgets.QPushButton(parent=self.frame_6)
        self.FIFO_Button.setGeometry(QtCore.QRect(20, 40, 181, 41))
        self.FIFO_Button.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #121212;\n"
"}")
        self.FIFO_Button.setObjectName("FIFO_Button")
        self.frame_7 = QtWidgets.QFrame(parent=MainWindow)
        self.frame_7.setGeometry(QtCore.QRect(1110, 60, 221, 221))
        self.frame_7.setStyleSheet("background-color: #1e1e1e;\n"
"border-radius: 5px;\n"
"border: 1px solid #555;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_12 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_12.setGeometry(QtCore.QRect(20, 10, 161, 20))
        self.label_12.setStyleSheet("color: white;\n"
"font-size: 16px;\n"
"border: 0;\n"
"")
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.Start_Button = QtWidgets.QPushButton(parent=self.frame_7)
        self.Start_Button.setGeometry(QtCore.QRect(20, 40, 181, 41))
        self.Start_Button.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #121212;\n"
"}")
        self.Start_Button.setObjectName("Start_Button")
        self.Next_Button = QtWidgets.QPushButton(parent=self.frame_7)
        self.Next_Button.setGeometry(QtCore.QRect(20, 100, 181, 41))
        self.Next_Button.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #121212;\n"
"}")
        self.Next_Button.setObjectName("Next_Button")
        self.Clear_Button = QtWidgets.QPushButton(parent=self.frame_7)
        self.Clear_Button.setGeometry(QtCore.QRect(20, 160, 181, 41))
        self.Clear_Button.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #121212;\n"
"}")
        self.Clear_Button.setObjectName("Clear_Button")
        self.frame = QtWidgets.QFrame(parent=MainWindow)
        self.frame.setGeometry(QtCore.QRect(30, 300, 1061, 91))
        self.frame.setStyleSheet("background-color: #1e1e1e;\n"
"border-radius: 5px;\n"
"border: 1px solid #555;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.Page_Sequence_Container = QtWidgets.QFrame(parent=self.frame)
        self.Page_Sequence_Container.setGeometry(QtCore.QRect(10, 30, 1041, 51))
        self.Page_Sequence_Container.setStyleSheet("border: 0;")
        self.Page_Sequence_Container.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Page_Sequence_Container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Page_Sequence_Container.setObjectName("Page_Sequence_Container")
        self.label_13 = QtWidgets.QLabel(parent=self.frame)
        self.label_13.setGeometry(QtCore.QRect(20, 10, 361, 20))
        self.label_13.setStyleSheet("color: white;\n"
"font-size: 16px;\n"
"border: 0;\n"
"")
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.frame_2 = QtWidgets.QFrame(parent=MainWindow)
        self.frame_2.setGeometry(QtCore.QRect(1110, 300, 221, 481))
        self.frame_2.setStyleSheet("background-color: #1e1e1e;\n"
"border-radius: 5px;\n"
"border: 1px solid #555;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_14 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(20, 10, 161, 20))
        self.label_14.setStyleSheet("color: white;\n"
"font-size: 16px;\n"
"border: 0;\n"
"")
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.Hit_Miss_Line_Edit = QtWidgets.QLineEdit(parent=self.frame_2)
        self.Hit_Miss_Line_Edit.setGeometry(QtCore.QRect(120, 280, 81, 41))
        self.Hit_Miss_Line_Edit.setStyleSheet("QLineEdit {\n"
"    background-color: #2d2d2d;\n"
"    color: white;\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    padding: 4px;\n"
"    font-size: 16px;\n"
"}")
        self.Hit_Miss_Line_Edit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Hit_Miss_Line_Edit.setReadOnly(False)
        self.Hit_Miss_Line_Edit.setObjectName("Hit_Miss_Line_Edit")
        self.Page_Faults_Line_Edit = QtWidgets.QLineEdit(parent=self.frame_2)
        self.Page_Faults_Line_Edit.setGeometry(QtCore.QRect(120, 360, 81, 41))
        self.Page_Faults_Line_Edit.setStyleSheet("QLineEdit {\n"
"    background-color: #2d2d2d;\n"
"    color: white;\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    padding: 4px;\n"
"    font-size: 16px;\n"
"}")
        self.Page_Faults_Line_Edit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Page_Faults_Line_Edit.setObjectName("Page_Faults_Line_Edit")
        self.Completion_Label = QtWidgets.QLabel(parent=self.frame_2)
        self.Completion_Label.setEnabled(True)
        self.Completion_Label.setGeometry(QtCore.QRect(10, 430, 201, 20))
        self.Completion_Label.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        border: 0;\n"
"}")
        self.Completion_Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Completion_Label.setObjectName("Completion_Label")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(90, 40, 111, 41))
        self.frame_4.setStyleSheet("border: 0;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_3.setStyleSheet("background-color: #D32F2F;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout.addWidget(self.frame_3)
        self.label_16 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_16.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        border: 0;\n"
"}")
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout.addWidget(self.label_16)
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_8.setGeometry(QtCore.QRect(90, 80, 91, 41))
        self.frame_8.setStyleSheet("border: 0;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_9 = QtWidgets.QFrame(parent=self.frame_8)
        self.frame_9.setStyleSheet("background-color: #2196F3;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_2.addWidget(self.frame_9)
        self.label_17 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_17.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        border: 0;\n"
"}")
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_2.addWidget(self.label_17)
        self.frame_10 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_10.setGeometry(QtCore.QRect(90, 120, 111, 41))
        self.frame_10.setStyleSheet("border: 0;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_11 = QtWidgets.QFrame(parent=self.frame_10)
        self.frame_11.setMaximumSize(QtCore.QSize(22, 16777215))
        self.frame_11.setStyleSheet("background-color: #4CAF50;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_3.addWidget(self.frame_11)
        self.label_18 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_18.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        border: 0;\n"
"}")
        self.label_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_3.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_19.setGeometry(QtCore.QRect(20, 50, 66, 23))
        self.label_19.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        border: 0;\n"
"}")
        self.label_19.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.line = QtWidgets.QFrame(parent=self.frame_2)
        self.line.setGeometry(QtCore.QRect(10, 260, 201, 1))
        self.line.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line.setStyleSheet("border: 0;\n"
"background-color: #555;")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(parent=self.frame_2)
        self.line_2.setGeometry(QtCore.QRect(10, 340, 201, 1))
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_2.setStyleSheet("border: 0;\n"
"background-color: #555;")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_20 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_20.setGeometry(QtCore.QRect(20, 290, 66, 23))
        self.label_20.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        border: 0;\n"
"}")
        self.label_20.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_21.setGeometry(QtCore.QRect(20, 370, 81, 23))
        self.label_21.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        border: 0;\n"
"}")
        self.label_21.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.label_25 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_25.setGeometry(QtCore.QRect(20, 210, 71, 23))
        self.label_25.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        border: 0;\n"
"}")
        self.label_25.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.line_3 = QtWidgets.QFrame(parent=self.frame_2)
        self.line_3.setGeometry(QtCore.QRect(10, 180, 201, 1))
        self.line_3.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_3.setStyleSheet("border: 0;\n"
"background-color: #555;")
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.Algorithm_Line_Edit = QtWidgets.QLineEdit(parent=self.frame_2)
        self.Algorithm_Line_Edit.setGeometry(QtCore.QRect(120, 200, 81, 41))
        self.Algorithm_Line_Edit.setStyleSheet("QLineEdit {\n"
"    background-color: #2d2d2d;\n"
"    color: white;\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    padding: 4px;\n"
"    font-size: 16px;\n"
"}")
        self.Algorithm_Line_Edit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Algorithm_Line_Edit.setReadOnly(True)
        self.Algorithm_Line_Edit.setObjectName("Algorithm_Line_Edit")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Page Replacement Simulator"))
        self.label_15.setText(_translate("MainWindow", "SIMULATION STATE"))
        self.label_22.setText(_translate("MainWindow", "Current Frame"))
        self.label_23.setText(_translate("MainWindow", "Added Page"))
        self.label_24.setText(_translate("MainWindow", "New Frame"))
        self.label_10.setText(_translate("MainWindow", "CONFIGURATION"))
        self.label.setText(_translate("MainWindow", "Length"))
        self.label_2.setText(_translate("MainWindow", "Frames"))
        self.Generate_Button.setText(_translate("MainWindow", "GENERATE"))
        self.label_3.setText(_translate("MainWindow", "Reference String"))
        self.Confirm_Button.setText(_translate("MainWindow", "CONFIRM"))
        self.label_9.setText(_translate("MainWindow", "PAGE REPLACEMENT ALGORITHM SIMULATOR"))
        self.label_11.setText(_translate("MainWindow", "OPTIONS"))
        self.LRU_Button.setText(_translate("MainWindow", "LRU"))
        self.Optimal_Button.setText(_translate("MainWindow", "OPTIMAL"))
        self.FIFO_Button.setText(_translate("MainWindow", "FIFO"))
        self.label_12.setText(_translate("MainWindow", "CONTROLS"))
        self.Start_Button.setText(_translate("MainWindow", "START"))
        self.Next_Button.setText(_translate("MainWindow", "NEXT"))
        self.Clear_Button.setText(_translate("MainWindow", "CLEAR"))
        self.label_13.setText(_translate("MainWindow", "REFERENCE STRING"))
        self.label_14.setText(_translate("MainWindow", "STATUS & INFO"))
        self.Completion_Label.setText(_translate("MainWindow", "SIMULATION COMPLETED!"))
        self.label_16.setText(_translate("MainWindow", "Removed"))
        self.label_17.setText(_translate("MainWindow", "Added"))
        self.label_18.setText(_translate("MainWindow", "Retained"))
        self.label_19.setText(_translate("MainWindow", "Legend"))
        self.label_20.setText(_translate("MainWindow", "Hit / Miss"))
        self.label_21.setText(_translate("MainWindow", "Page Faults"))
        self.label_25.setText(_translate("MainWindow", "Algorithm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
